POST http://localhost:3002/signin 
content-Type: application/json

{ 
    "username": "yourUsername",
    "password": "yourPassword", 
    "email": "yourEmail@example.com",
    "name": "Your Name"
}

###

POST http://localhost:3002/login
content-Type: application/json

{
    "email": "yourEmail@example.com",
    "password": "yourPassword"
}

###

POST http://localhost:3002/api/create-resume
content-Type: application/json


{
    "title": "yourResumeTitle",
    "personalInfo": {
        "firstName": "yourFirstName",
        "lastName": "yourLastName",
        "jobTitle": "yourJobTitle",
        "address": "yourAddress",
        "phone": "yourPhoneNumber",
        "email": "yourEmail@example.com",
        "summary": "yourSummary"
    },
    "experience": [
        {
            "title": "yourExperienceTitle",
            "companyName": "yourCompanyName",
            "city": "yourCity",
            "state": "yourState",
            "startDate": "yourStartDate",
            "endDate": "yourEndDate",
            "description": "yourDescription"
        }
    ],
    "education": [
        {
            "universityName": "yourSchool",
            "degree": "yourDegree",
            "fieldofstudy": "yourFieldOfStudy",
            "startDate": "yourStartDate",
            "endDate": "yourEndDate",
            "description": "yourDescription"
        }
    ],
    "skills": [
        {
            "name": "yourSkillName",
            "rating": "yourSkillRating"
        }
    ],
    "themeColor": "yourThemeColor"
}