POST http://localhost:3002/signup HTTP/1.1
content-Type: application/json

{ 
    "username": "yourUsername",
    "password": "yourPassword", 
    "email": "yourEmail@example.com",
    "name": "Your Name"
}