import { useState, useEffect } from "react";
import Button from "@mui/material/Button";
import DeleteIcon from "@mui/icons-material/Delete";
import CircularProgress from "@mui/material/CircularProgress";
import { toast } from "react-toastify";
import Checkbox from "@mui/material/Checkbox";
import FormControlLabel from "@mui/material/FormControlLabel";
import TextEditor from "react-simple-wysiwyg";
import { v4 as uuidv4 } from "uuid";
import { useResume } from "../../../../context/ResumeContext.jsx";
import { BASE_URL } from "../../../../axiosConfig.js";

// Default structure for an education entry
const defaultEducation = {
  id: uuidv4(),
  institution: "",
  field: "",
  degree: "",
  startDate: "",
  endDate: "",
  currentlyStudying: false,
  description: "",
};

export default function EducationForm({ enableNext }) {
  const { resumeData, updateEducation, updateResumeSection } = useResume();
  const [loading, setLoading] = useState(false);
  const [wasValidated, setWasValidated] = useState(false);

  const [education, setEducation] = useState([{ ...defaultEducation }]);

  // Load existing education data from resume context (if any)
  useEffect(() => {
    if (
      Array.isArray(resumeData?.education) &&
      resumeData.education.length > 0 &&
      JSON.stringify(resumeData.education) !== JSON.stringify(education)
    ) {
      setEducation(resumeData.education);
      enableNext(true);
    }
  }, [resumeData]);




  const handleChange = (e, index) => {
    const { name, value, type, checked } = e.target;
    const updated = education.map((item, i) =>
      i === index
        ? {
          ...item,
          [name]: type === "checkbox" ? checked : value,
          ...(name === "currentlyStudying" && checked ? { endDate: "" } : {}),
        }
        : item
    );
    setEducation(updated);
    updateEducation(updated);
  };


  const handleAI = async (index) => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      if (!token) {
        toast.error("User not authenticated");
        setLoading(false);
        return;
      }

      const edu = education[index];
      const prompt = `Generate exactly 2 short lines summarizing the academic experience of someone with a ${edu?.degree} in ${edu?.field} from ${edu?.institution}. Focus on practical skills, projects, or learning outcomes. Avoid placeholders like [Specific Area]. Keep the language concise and ready for a resume.`;

      const response = await fetch(`${BASE_URL}/generate-summary`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          section: "education",
          customPrompt: prompt,
        }),
      });

      const data = await response.json();

      if (data.responseText) {
        const cleanResponse = data.responseText
          .split("•")
          .filter(Boolean)
          .map((point) => `• ${point.trim()}`)
          .join("\n");

        const updated = [...education];
        updated[index].description = cleanResponse;

        setEducation(updated);
        updateEducation(updated);

        toast.success("Description generated by AI");
      } else {
        toast.error("AI did not return a response");
      }
    } catch (err) {
      console.error("AI Error:", err);
      toast.error("Failed to generate summary.");
    } finally {
      setLoading(false);
    }
  };


  const handleDescriptionChange = (value, index) => {
    const updated = [...education];
    updated[index].description = typeof value === "string" ? value : "";
    setEducation(updated);
    updateEducation(updated);
  };

  const addEducation = () => {
    const newEdu = [...education, { ...defaultEducation, id: uuidv4() }];
    setEducation(newEdu);
    updateEducation(newEdu);
  };

  const removeEducation = (index) => {
    const updated = education.filter((_, i) => i !== index);
    setEducation(updated);
    updateEducation(updated);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setWasValidated(true);
    setLoading(true);

    try {
      const isValid = education.every(
        (item) =>
          item.institution.trim() !== "" &&
          item.degree.trim() !== "" &&
          item.field.trim() !== "" &&
          item.startDate !== "" &&
          (item.currentlyStudying || item.endDate !== "") &&
          item.description.trim() !== ""
      );

      if (!isValid) {
        toast.error("Please fill all required fields");
        enableNext(false);
        setLoading(false);
        return;
      }

      // Trim dates to "YYYY-MM-DD"
      const trimmedEducation = education.map(item => ({
        ...item,
        startDate: item.startDate?.slice(0, 10),
        endDate: item.currentlyStudying ? null : item.endDate?.slice(0, 10),
      }));

      updateEducation(trimmedEducation);


      await updateResumeSection({ education: trimmedEducation }); //  Save to backend
      toast.success("Education information saved");
      enableNext(true); //  Enable next only after successful save
    } catch (error) {
      console.error("Error saving education:", error);
      toast.error("Failed to save education to server");
      enableNext(false);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="forms-cards pt-2 pb-5 ps-3 pe-3 rounded-4 mt-4"
      style={{
        height: "fit-content",
        borderTop: "5px solid #0d6ff2f2",
                    boxShadow: "rgba(0, 0, 0, 0.1) 1px 1px 12px 0px, rgba(0, 0, 0, 0.1) 4px 4px 12px 0px,  rgba(255, 255, 255, 0.1) 0px 0px 0px 1px inset"

      }}
    >
      <h4 className="fw-bold pb-1 m-0 mt-2">Education</h4>
      <p className="pb-4">Add your education details</p>

      <form className="needs-validation" noValidate onSubmit={handleSubmit}>
        <div className="container g-2  justify-content-between border border-1 border-dark rounded-3 p-3 p-sm-3 w-full">
          {education.map((item, index) => (
            <div key={item.id} className="row g-2 justify-content-between mb-4">
              {/* Institution */}
              <div className="col-md-4 d-flex flex-column">
                <label className="fw-medium">University Name</label>
                <input
                  type="text"
                  name="institution"
                  value={item.institution}
                  onChange={(e) => handleChange(e, index)}
                  className={`form-control p-1 ${wasValidated && !item.institution.trim() ? "is-invalid" : ""}`}
                  required
                />
                {wasValidated && !item.institution.trim() && (
                  <div className="invalid-feedback">Institution name is required.</div>
                )}
              </div>

              {/* Degree */}
              <div className="col-md-4 d-flex flex-column">
                <label className="fw-medium">Degree</label>
                <input
                  type="text"
                  name="degree"
                  value={item.degree}
                  onChange={(e) => handleChange(e, index)}
                  className={`form-control p-1 ${wasValidated && !item.degree.trim() ? "is-invalid" : ""}`}
                  required
                />
                {wasValidated && !item.degree.trim() && (
                  <div className="invalid-feedback">Degree is required.</div>
                )}
              </div>

              {/* Field */}
              <div className="col-md-4 d-flex flex-column">
                <label className="fw-medium">Field of Study</label>
                <input
                  type="text"
                  name="field"
                  value={item.field}
                  onChange={(e) => handleChange(e, index)}
                  className={`form-control p-1 ${wasValidated && !item.field.trim() ? "is-invalid" : ""}`}
                  required
                />
                {wasValidated && !item.field.trim() && (
                  <div className="invalid-feedback">Field is required.</div>
                )}
              </div>



              <div className="form-education  d-flex flex-row gap-2 justify-content-between align-content-center ">
                {/* Start Date */}
                <div className=" d-flex flex-column" style={{ width: "100%" }}>
                  <label className="fw-medium">Start Date</label>
                  <input
                    type="date"
                    name="startDate"
                    value={item.startDate}
                    onChange={(e) => handleChange(e, index)}
                    className={`form-control p-1 ${wasValidated && !item.startDate ? "is-invalid" : ""}`}
                    required
                  />
                  {wasValidated && !item.startDate.trim() && (
                    <div className="invalid-feedback">startDate is required.</div>
                  )}
                </div>

                {/* End Date */}
                <div className=" mb-4 d-flex flex-column" style={{ width: "100%" }}>
                  <label className="fw-medium">End Date</label>
                  <input
                    type="date"
                    name="endDate"
                    value={item.endDate}
                    onChange={(e) => handleChange(e, index)}
                    className={`form-control p-1 ${wasValidated && !item.currentlyStudying && !item.endDate ? "is-invalid" : ""}`}
                    required={!item.currentlyStudying}
                    disabled={item.currentlyStudying}
                  />
                  {wasValidated && !item.endDate && (
                    <div className="invalid-feedback">endDate is required.</div>
                  )}
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={item.currentlyStudying}
                        onChange={(e) => handleChange(e, index)}
                        name="currentlyStudying"
                      />
                    }
                    label="Currently studying here"
                  />
                </div>
              </div>

             {/* Generative AI Button */}
                                <div className="d-flex justify-content-between align-items-center px-2 ">
          <div></div>
          <Button
            variant="outlined"
            color="info"
            onClick={handleAI}
            disabled={loading}
            type="button"
            sx={{
                borderColor: "rgba(193, 87, 246, 0.95)",
              backgroundColor: "rgba(255, 255, 255, 0.95)",
              color: "rgba(168, 36, 220, 0.95)",
              fontWeight: 400,
            }}
            >
            {loading ? <CircularProgress size={18} /> : "Generate From AI"}
          </Button>
        </div>


              {/* Description */}
              <div className="col-12 d-flex flex-column mt-2">
                <label className="fw-medium">Description</label>
                <TextEditor
                  value={item.description}
                  onChange={(e) => handleDescriptionChange(e.target.value, index)}
                  style={{
                    minHeight: "150px",
                    border: "1px solid #ccc",
                    borderRadius: "4px",
                    padding: "10px",
                  }}
                  className={`${wasValidated && !item.description.trim() ? "is-invalid" : ""}`}
                />
                {wasValidated && !item.description.trim() && (
                  <div className="invalid-feedback d-block mt-1">Description is required.</div>
                )}
              </div>

              {/* Buttons */}
              <div className="education-addbtn col-12 d-flex gap-4 justify-content-between align-items-center mt-3">
                {(education.length > 1 && <Button
                  variant="contained"
                  color="error"
                  startIcon={<DeleteIcon />}
                  onClick={() => removeEducation(index)}
                  disabled={education.length === 1}
                >
                  Remove Education
                </Button>)}

                {index === education.length - 1 && (
                  <Button variant="contained" onClick={addEducation}>
                    Add Education
                  </Button>
                )}
              </div>

            </div>
          ))}
        </div>

        <div className="d-flex justify-content-center mt-4">

          <Button
            variant="contained"
            color="primary"
            type="submit"
            disabled={loading}
            sx={{ width: "7rem", fontWeight: 600, fontSize: "1rem" }}
          >
            {loading ? <CircularProgress size={20} /> : "Save"}
          </Button>
        </div>
      </form>
    </div>
  );
}
